name: CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:18
    timeout-minutes: 15
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.8

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint
